from fastapi import FastAPI, HTTPException, Request, Response, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
from starlette.middleware.sessions import SessionMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from pydantic import BaseModel
from typing import Optional
import os
import re
from datetime import datetime, timezone, timedelta
from io import BytesIO
from uuid import uuid4
import pandas as pd
from import_tura import (
    create_grm_request,
    fail,
    get_tracking,
    get_grm_request_work_orders,
    ingest_grm_request,
    poll_grm_request,
    wait_and_ingest_grm_request,
)
from db import get_db

SESSION_SECRET = os.environ.get("KOLICA_SESSION_SECRET", "kolica-local-session-secret-v1")
KOM_PREVIEW_TTL_MINUTES = 30
kom_import_previews: dict[str, dict] = {}

app = FastAPI(title="Kolica Scan API")
app.add_middleware(SessionMiddleware, secret_key=SESSION_SECRET, same_site="lax")

# CORS Configuration
cors_origins = os.environ.get(
    "KOLICA_CORS_ORIGINS",
    "*"
).split(",")

app.add_middleware(
    CORSMiddleware,
    allow_origins=[origin.strip() for origin in cors_origins],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Serve frontend
frontend_path = os.path.join(os.path.dirname(__file__), "..", "frontend")
app.mount("/static", StaticFiles(directory=frontend_path), name="static")

class LoginRequest(BaseModel):
    username: str
    password: str

# Helper to format vrijeme for frontend compatibility (%Y-%m-%d %H:%M:%S string)
def format_row_vrijeme(row):
    if row and row.get("vrijeme"):
        val = row["vrijeme"]
        if isinstance(val, datetime):
            row["vrijeme"] = val.strftime("%Y-%m-%d %H:%M:%S")
        elif isinstance(val, str):
            pass
    return row

def format_rows_vrijeme(rows):
    return [format_row_vrijeme(dict(r)) for r in rows]

@app.get("/", include_in_schema=False)
def root():
    return FileResponse(os.path.join(frontend_path, "index.html"))


@app.get("/auth/me")
def auth_me(request: Request):
    user = get_current_user_or_none(request)
    if not user:
        raise HTTPException(status_code=401, detail="Niste prijavljeni.")
    return user


@app.post("/auth/login")
def auth_login(body: LoginRequest, request: Request):
    with get_db() as conn:
        row = conn.execute(
            """
            SELECT username, password, role, display_name, active
            FROM korisnici
            WHERE username = %s
            """,
            (body.username.strip(),),
        ).fetchone()

    if not row or row["password"] != body.password or not row["active"]:
        raise HTTPException(status_code=401, detail="Neispravno korisničko ime ili lozinka.")

    request.session["auth"] = {
        "username": row["username"],
    }
    return {
        "username": row["username"],
        "role": row["role"],
        "display_name": row["display_name"] or row["username"],
    }


@app.post("/auth/logout")
def auth_logout(request: Request):
    request.session.pop("auth", None)
    return {"ok": True}


# ─── DB INIT ────────────────────────────────────────────────────────────────

def init_db():
    try:
        with get_db() as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    CREATE TABLE IF NOT EXISTS korisnici (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username TEXT NOT NULL UNIQUE,
                        password TEXT NOT NULL,
                        role TEXT NOT NULL,
                        display_name TEXT,
                        active BOOLEAN NOT NULL DEFAULT TRUE
                    )
                """)
                cur.execute("""
                    CREATE TABLE IF NOT EXISTS dijelovi (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        tura TEXT NOT NULL,
                        barcode TEXT NOT NULL,
                        nalog TEXT,
                        broj_rn TEXT,
                        part TEXT,
                        kom INTEGER NOT NULL DEFAULT 1,
                        scan_count INTEGER NOT NULL DEFAULT 0,
                        materijal TEXT,
                        klasifikacija TEXT,
                        debljina NUMERIC(6, 2),
                        status TEXT NOT NULL DEFAULT 'IZREZANO',
                        kolica INTEGER,
                        tura_br TEXT,
                        operater TEXT,
                        vrijeme TIMESTAMPTZ
                    )
                """)
                
                # Check / Add missing columns
                cur.execute("ALTER TABLE dijelovi ADD COLUMN IF NOT EXISTS broj_rn TEXT")
                cur.execute("ALTER TABLE dijelovi ADD COLUMN IF NOT EXISTS kom INTEGER DEFAULT 1")
                cur.execute("ALTER TABLE dijelovi ADD COLUMN IF NOT EXISTS scan_count INTEGER DEFAULT 0")
                cur.execute("ALTER TABLE dijelovi ADD COLUMN IF NOT EXISTS klasifikacija TEXT")
                cur.execute("ALTER TABLE dijelovi ADD COLUMN IF NOT EXISTS tura_br TEXT")
                
                # Fix any invalid quantities/scans
                cur.execute("UPDATE dijelovi SET kom = 1 WHERE kom IS NULL OR kom < 1")
                cur.execute("""
                    UPDATE dijelovi
                    SET scan_count = CASE
                        WHEN (scan_count IS NULL OR scan_count = 0) AND status = 'SAVIJENO' THEN kom
                        WHEN scan_count IS NULL THEN 0
                        WHEN scan_count < 0 THEN 0
                        WHEN scan_count > kom THEN kom
                        ELSE scan_count
                    END
                """)
                
                # Indexes
                cur.execute("CREATE INDEX IF NOT EXISTS idx_barcode ON dijelovi(barcode)")
                cur.execute("CREATE INDEX IF NOT EXISTS idx_tura ON dijelovi(tura)")
                cur.execute("CREATE INDEX IF NOT EXISTS idx_nalog ON dijelovi(nalog)")
                cur.execute("CREATE INDEX IF NOT EXISTS idx_dijelovi_status ON dijelovi(status)")
                cur.execute("CREATE INDEX IF NOT EXISTS idx_dijelovi_lower_barcode ON dijelovi (lower(barcode))")
            conn.commit()
            print("PostgreSQL database initialized successfully.")
    except Exception as e:
        print(f"Error initializing database: {e}")

init_db()


# ─── MODELS ─────────────────────────────────────────────────────────────────

class StatusUpdate(BaseModel):
    status: str
    kolica: Optional[int] = None

class KolicaUpdate(BaseModel):
    kolica: int


class KomUpdate(BaseModel):
    kom: int


class TijekUpdate(BaseModel):
    scan_count: int


class AdminKolicaUpdate(BaseModel):
    kolica: Optional[int] = None


class GrmRequestParams(BaseModel):
    from_date: str
    to_date: str
    admctr: str
    request_id: Optional[str] = None


class GrmSelectionIngest(BaseModel):
    sifradn: list[str]


class KomImportApply(BaseModel):
    token: str


def get_current_user_or_none(request: Request):
    auth = request.session.get("auth")
    if not auth:
        return None

    try:
        with get_db() as conn:
            row = conn.execute(
                """
                SELECT username, role, display_name, active
                FROM korisnici
                WHERE username = %s
                """,
                (auth.get("username"),),
            ).fetchone()
    except Exception:
        return None

    if not row or not row["active"]:
        request.session.pop("auth", None)
        return None

    return {
        "username": row["username"],
        "role": row["role"],
        "display_name": row["display_name"] or row["username"],
    }


def require_auth(request: Request):
    user = get_current_user_or_none(request)
    if not user:
        raise HTTPException(status_code=401, detail="Prijava je obavezna.")
    return user


def require_admin(request: Request):
    user = require_auth(request)
    if user["role"] != "admin":
        raise HTTPException(status_code=403, detail="Ova akcija je dozvoljena samo administratoru.")
    return user


def prune_kom_previews():
    now = datetime.now()
    expired = [
        token for token, payload in kom_import_previews.items()
        if payload["expires_at"] <= now
    ]
    for token in expired:
        kom_import_previews.pop(token, None)


def normalize_excel_barcode(value):
    return str(value or "").strip().upper()


def normalize_excel_header(value):
    text = str(value or "")
    text = text.replace("\ufeff", " ").replace("\u00a0", " ")
    text = text.replace("_", " ")
    text = re.sub(r"\s+", " ", text).strip().lower()
    return text


def parse_kom_value(value):
    try:
        number = int(float(str(value).strip()))
    except (TypeError, ValueError):
        return None
    return number if number >= 1 else None


def build_kom_preview_for_tura(tura: str, filename: str, excel_bytes: bytes):
    try:
        raw_df = pd.read_excel(BytesIO(excel_bytes), sheet_name="Instances", header=None, dtype=object)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail="Excel nema sheet 'Instances'.") from exc
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"Excel nije moguće učitati: {exc}") from exc

    header_row_index = None
    required_headers = {
        normalize_excel_header("opc_barkod_potrebe"),
        normalize_excel_header("BROJ MAX"),
    }
    scan_limit = min(len(raw_df), 50)
    for idx in range(scan_limit):
        row_values = {
            normalize_excel_header(value)
            for value in raw_df.iloc[idx].tolist()
            if normalize_excel_header(value)
        }
        if required_headers.issubset(row_values):
            header_row_index = idx
            break

    if header_row_index is None:
        sample_rows = []
        for idx in range(min(len(raw_df), 5)):
            values = [
                str(value).strip()
                for value in raw_df.iloc[idx].tolist()
                if str(value).strip() and str(value).strip().lower() != "nan"
            ]
            if values:
                sample_rows.append(" | ".join(values[:8]))
        preview = " || ".join(sample_rows) if sample_rows else "nema čitljivih redova"
        raise HTTPException(
            status_code=400,
            detail=(
                "Excel nema obavezne kolone: opc_barkod_potrebe, BROJ MAX. "
                f"Sheet 'Instances' je učitan, ali header red nije pronađen. "
                f"Prvi redovi izgledaju ovako: {preview}"
            ),
        )

    df = raw_df.iloc[header_row_index + 1 :].copy()
    df.columns = [str(col).strip() for col in raw_df.iloc[header_row_index].tolist()]
    df.columns = [str(col).strip() for col in df.columns]
    normalized_columns = {normalize_excel_header(col): col for col in df.columns}

    def resolve_excel_column(*aliases: str):
        for alias in aliases:
            resolved = normalized_columns.get(normalize_excel_header(alias))
            if resolved:
                return resolved
        return None

    barcode_column = resolve_excel_column("opc_barkod_potrebe", "opc barkod potrebe")
    kom_column = resolve_excel_column("BROJ MAX", "BROJ_MAX", "broj max", "broj_max")

    missing = []
    if not barcode_column:
        missing.append("opc_barkod_potrebe")
    if not kom_column:
        missing.append("BROJ MAX")
    if missing:
        available_columns = ", ".join(df.columns[:12])
        if len(df.columns) > 12:
            available_columns += ", ..."
        raise HTTPException(
            status_code=400,
            detail=(
                f"Excel nema obavezne kolone: {', '.join(missing)}. "
                f"Nađeni stupci: {available_columns}"
            )
        )

    with get_db() as conn:
        rows = conn.execute(
            "SELECT * FROM dijelovi WHERE tura = %s ORDER BY id",
            (tura,)
        ).fetchall()

    if not rows:
        raise HTTPException(status_code=404, detail=f"Tura '{tura}' nije pronađena.")

    row_dicts = [dict(row) for row in rows]
    rows_by_barcode: dict[str, list[dict]] = {}
    for row in row_dicts:
        barcode = normalize_excel_barcode(row["barcode"])
        rows_by_barcode.setdefault(barcode, []).append(row)

    invalid_rows = []
    grouped: dict[str, dict] = {}
    total_rows = len(df)

    for idx, raw in df.iterrows():
        barcode = normalize_excel_barcode(raw.get(barcode_column))
        if not barcode:
            invalid_rows.append({
                "row_number": int(idx) + 2,
                "barcode": "",
                "reason": f"Prazan {barcode_column}",
            })
            continue
        kom_value = parse_kom_value(raw.get(kom_column))
        if kom_value is None:
            invalid_rows.append({
                "row_number": int(idx) + 2,
                "barcode": barcode,
                "reason": f"Neispravan {kom_column}: {raw.get(kom_column)}",
            })
            continue
        bucket = grouped.setdefault(
            barcode,
            {"kom_values": set(), "row_numbers": [], "raw_count": 0}
        )
        bucket["kom_values"].add(kom_value)
        bucket["row_numbers"].append(int(idx) + 2)
        bucket["raw_count"] += 1

    conflicts = []
    missing_in_tura = []
    clean_matches = []
    unchanged_matches = 0
    changed_row_count = 0
    updates = []

    for barcode, payload in grouped.items():
        kom_values = sorted(payload["kom_values"])
        if len(kom_values) > 1:
            conflicts.append({
                "barcode": barcode,
                "kom_values": kom_values,
                "row_numbers": payload["row_numbers"],
            })
            continue

        target_rows = rows_by_barcode.get(barcode, [])
        if not target_rows:
            missing_in_tura.append({
                "barcode": barcode,
                "kom": kom_values[0],
            })
            continue

        new_kom = kom_values[0]
        changed_ids = []
        sample_old_kom = None
        for row in target_rows:
            old_kom = max(int(row["kom"] or 1), 1)
            if sample_old_kom is None:
                sample_old_kom = old_kom
            if old_kom != new_kom:
                changed_ids.append(int(row["id"]))
        if changed_ids:
            changed_row_count += len(changed_ids)
        else:
            unchanged_matches += 1

        updates.append({
            "barcode": barcode,
            "kom": new_kom,
            "row_ids": [int(row["id"]) for row in target_rows],
        })
        clean_matches.append({
            "barcode": barcode,
            "kom": new_kom,
            "match_count": len(target_rows),
            "old_kom": sample_old_kom,
            "changed": bool(changed_ids),
        })

    token = uuid4().hex
    now = datetime.now()
    kom_import_previews[token] = {
        "token": token,
        "tura": tura,
        "filename": filename,
        "generated_at": now,
        "expires_at": now + timedelta(minutes=KOM_PREVIEW_TTL_MINUTES),
        "updates": updates,
    }

    return {
        "token": token,
        "tura": tura,
        "filename": filename,
        "sheet": "Instances",
        "stats": {
            "excel_rows_total": total_rows,
            "unique_barcodes": len(grouped),
            "invalid_rows": len(invalid_rows),
            "conflict_barcodes": len(conflicts),
            "missing_in_tura": len(missing_in_tura),
            "clean_matches": len(clean_matches),
            "changed_rows": changed_row_count,
            "unchanged_matches": unchanged_matches,
        },
        "conflicts": conflicts[:50],
        "missing_in_tura_details": missing_in_tura[:50],
        "invalid_rows_details": invalid_rows[:50],
        "sample_matches": clean_matches[:50],
    }


# ─── ENDPOINTS ──────────────────────────────────────────────────────────────

@app.get("/ture")
def get_ture(request: Request):
    """Vrati popis svih tura."""
    require_auth(request)
    with get_db() as conn:
        rows = conn.execute(
            "SELECT DISTINCT tura FROM dijelovi ORDER BY tura"
        ).fetchall()
    return [r["tura"] for r in rows]


@app.get("/dijelovi")
def get_dijelovi(request: Request, tura: Optional[str] = None):
    """Vrati sve dijelove, opcionalno filtrirane po turi."""
    require_auth(request)
    with get_db() as conn:
        if tura:
            rows = conn.execute(
                "SELECT * FROM dijelovi WHERE tura = %s ORDER BY id", (tura,)
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT * FROM dijelovi ORDER BY tura, id"
            ).fetchall()
    return format_rows_vrijeme(rows)


@app.get("/scan/{barcode}")
def scan_barcode(barcode: str, request: Request):
    """
    Pretraži sve ture za barcode.
    Vrati prvi IZREZANO redak — ili info da nema IZREZANO.
    """
    user = require_auth(request)
    with get_db() as conn:
        # Sve koji odgovaraju barcodeu
        all_rows = conn.execute(
            "SELECT * FROM dijelovi WHERE LOWER(barcode) = LOWER(%s)",
            (barcode,)
        ).fetchall()

        if not all_rows:
            raise HTTPException(status_code=404, detail=f"Barcode '{barcode}' nije pronađen ni u jednoj turi.")

        # Traži i zaključaj prvi IZREZANO s slobodnim skeniranjima
        target = conn.execute(
            """
            SELECT * FROM dijelovi 
            WHERE LOWER(barcode) = LOWER(%s)
              AND status = 'IZREZANO'
              AND scan_count < kom
            ORDER BY id
            FOR UPDATE SKIP LOCKED
            LIMIT 1
            """,
            (barcode,)
        ).fetchone()

        if not target:
            statusi = list({r["status"] for r in all_rows})
            sample_row = format_row_vrijeme(dict(all_rows[0]))
            kom = max(int(sample_row["kom"] or 1), 1)
            scan_count = min(max(int(sample_row["scan_count"] or 0), 0), kom)
            return {
                "found": True,
                "has_izrezano": False,
                "total": len(all_rows),
                "statusi": statusi,
                "row": sample_row,
                "completed_progress": f"{scan_count} od {kom}",
            }

        kom = max(int(target["kom"] or 1), 1)
        current_scan_count = min(max(int(target["scan_count"] or 0), 0), kom)
        new_scan_count = min(current_scan_count + 1, kom)
        scan_time = datetime.now(timezone.utc)
        
        conn.execute(
            """
            UPDATE dijelovi 
            SET status = 'SAVIJENO', scan_count = %s, vrijeme = %s, operater = %s 
            WHERE id = %s
            """,
            (new_scan_count, scan_time, user["display_name"], target["id"])
        )
        conn.commit()

        updated = conn.execute(
            "SELECT * FROM dijelovi WHERE id = %s", (target["id"],)
        ).fetchone()

    return {
        "found": True,
        "has_izrezano": True,
        "remaining_scans": max(kom - new_scan_count, 0),
        "row": format_row_vrijeme(dict(updated))
    }


@app.patch("/dijelovi/{id}/status")
def update_status(id: int, body: StatusUpdate, request: Request):
    """Ručna promjena statusa. Ako status nije SAVIJENO, briše kolica."""
    require_admin(request)
    with get_db() as conn:
        row = conn.execute("SELECT * FROM dijelovi WHERE id = %s", (id,)).fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Redak nije pronađen.")

        # Ako se mijenja s SAVIJENO na nešto drugo — briši kolica
        kom = max(int(row["kom"] or 1), 1)
        scan_count = min(max(int(row["scan_count"] or 0), 0), kom)
        kolica = row["kolica"]
        if row["status"] == "SAVIJENO" and body.status != "SAVIJENO":
            kolica = None

        vrijeme = row["vrijeme"]
        if body.status == "IZREZANO":
            scan_count = 0
            vrijeme = None
        elif body.status == "SAVIJENO":
            scan_count = kom
            if not vrijeme:
                vrijeme = datetime.now(timezone.utc)

        conn.execute(
            "UPDATE dijelovi SET status = %s, kolica = %s, scan_count = %s, vrijeme = %s WHERE id = %s",
            (body.status, kolica, scan_count, vrijeme, id)
        )
        conn.commit()
        updated = conn.execute("SELECT * FROM dijelovi WHERE id = %s", (id,)).fetchone()
        
    return format_row_vrijeme(dict(updated))


@app.patch("/dijelovi/{id}/kolica")
def update_kolica(id: int, body: KolicaUpdate, request: Request):
    """Dodijeli broj kolica retku."""
    user = require_auth(request)
    with get_db() as conn:
        row = conn.execute("SELECT * FROM dijelovi WHERE id = %s", (id,)).fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Redak nije pronađen.")
        conn.execute(
            "UPDATE dijelovi SET kolica = %s, operater = %s WHERE id = %s",
            (body.kolica, user["display_name"], id)
        )
        conn.commit()
        updated = conn.execute("SELECT * FROM dijelovi WHERE id = %s", (id,)).fetchone()
    return format_row_vrijeme(dict(updated))


@app.patch("/dijelovi/{id}/kolica-admin")
def update_kolica_admin(id: int, body: AdminKolicaUpdate, request: Request):
    """Rucna admin promjena kolica, ukljucujuci brisanje vrijednosti."""
    user = require_admin(request)
    with get_db() as conn:
        row = conn.execute("SELECT * FROM dijelovi WHERE id = %s", (id,)).fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Redak nije pronaden.")

        kolica = body.kolica
        conn.execute(
            "UPDATE dijelovi SET kolica = %s, operater = %s WHERE id = %s",
            (kolica, user["display_name"], id)
        )
        conn.commit()
        updated = conn.execute("SELECT * FROM dijelovi WHERE id = %s", (id,)).fetchone()
    return format_row_vrijeme(dict(updated))


@app.patch("/dijelovi/{id}/kom")
def update_kom(id: int, body: KomUpdate, request: Request):
    require_admin(request)
    kom = int(body.kom)
    if kom < 1:
        raise HTTPException(status_code=400, detail="KOM. mora biti barem 1.")

    with get_db() as conn:
        row = conn.execute("SELECT * FROM dijelovi WHERE id = %s", (id,)).fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Redak nije pronađen.")

        scan_count = min(max(int(row["scan_count"] or 0), 0), kom)
        status = row["status"]
        if scan_count == 0 and status == "SAVIJENO":
            status = "IZREZANO"
        elif scan_count > 0 and status == "IZREZANO":
            status = "SAVIJENO"

        conn.execute(
            "UPDATE dijelovi SET kom = %s, scan_count = %s, status = %s WHERE id = %s",
            (kom, scan_count, status, id)
        )
        conn.commit()
        updated = conn.execute("SELECT * FROM dijelovi WHERE id = %s", (id,)).fetchone()
    return format_row_vrijeme(dict(updated))


@app.patch("/dijelovi/{id}/tijek")
def update_tijek(id: int, body: TijekUpdate, request: Request):
    require_admin(request)
    with get_db() as conn:
        row = conn.execute("SELECT * FROM dijelovi WHERE id = %s", (id,)).fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Redak nije pronaden.")

        kom = max(int(row["kom"] or 1), 1)
        scan_count = int(body.scan_count)
        if scan_count < 0 or scan_count > kom:
            raise HTTPException(status_code=400, detail=f"TIJEK mora biti izmedu 0 i {kom}.")

        status = "SAVIJENO" if scan_count > 0 else "IZREZANO"
        vrijeme = row["vrijeme"]
        if scan_count == 0:
            vrijeme = None
        elif not vrijeme:
            vrijeme = datetime.now(timezone.utc)

        conn.execute(
            "UPDATE dijelovi SET scan_count = %s, status = %s, vrijeme = %s WHERE id = %s",
            (scan_count, status, vrijeme, id)
        )
        conn.commit()
        updated = conn.execute("SELECT * FROM dijelovi WHERE id = %s", (id,)).fetchone()
    return format_row_vrijeme(dict(updated))


@app.get("/statistike")
def get_statistike(request: Request, tura: Optional[str] = None):
    """Statistike po turi ili sve zajedno."""
    require_auth(request)
    with get_db() as conn:
        if tura:
            where = "WHERE tura = %s"
            where_and = "WHERE tura = %s AND"
            params = (tura,)
        else:
            where = ""
            where_and = "WHERE"
            params = ()

        def get_count(sql, p):
            res = conn.execute(sql, p).fetchone()
            if res:
                return list(res.values())[0]
            return 0

        stats = {
            "ukupno":        get_count(f"SELECT COUNT(*) FROM dijelovi {where}", params),
            "savijeno":      get_count(f"SELECT COUNT(*) FROM dijelovi {where_and} status='SAVIJENO'", params),
            "izrezano":      get_count(f"SELECT COUNT(*) FROM dijelovi {where_and} status='IZREZANO'", params),
            "krivo_savijeno":get_count(f"SELECT COUNT(*) FROM dijelovi {where_and} status='KRIVO SAVIJENO'", params),
            "s_kolicima":    get_count(f"SELECT COUNT(*) FROM dijelovi {where_and} kolica IS NOT NULL", params),
            "bez_kolica":    get_count(f"SELECT COUNT(*) FROM dijelovi {where_and} kolica IS NULL", params),
        }
    return stats


@app.post("/kom-import/preview")
async def preview_kom_import(
    request: Request,
    tura: str = Form(...),
    file: UploadFile = File(...),
):
    require_admin(request)
    prune_kom_previews()
    if not file.filename:
        raise HTTPException(status_code=400, detail="Nije odabran Excel file.")

    contents = await file.read()
    if not contents:
        raise HTTPException(status_code=400, detail="Odabrani Excel file je prazan.")

    return build_kom_preview_for_tura(tura=tura, filename=file.filename, excel_bytes=contents)


@app.post("/kom-import/apply")
def apply_kom_import(body: KomImportApply, request: Request):
    require_admin(request)
    prune_kom_previews()
    preview = kom_import_previews.get(body.token)
    if not preview:
        raise HTTPException(status_code=404, detail="Preview token nije pronađen ili je istekao.")

    with get_db() as conn:
        updated_rows = 0
        updated_barcodes = 0
        for item in preview["updates"]:
            new_kom = int(item["kom"])
            for row_id in item["row_ids"]:
                row = conn.execute("SELECT * FROM dijelovi WHERE id = %s", (row_id,)).fetchone()
                if not row:
                    continue
                scan_count = min(max(int(row["scan_count"] or 0), 0), new_kom)
                status = "SAVIJENO" if scan_count > 0 else "IZREZANO"
                vrijeme = row["vrijeme"]
                if scan_count == 0:
                    vrijeme = None
                conn.execute(
                    "UPDATE dijelovi SET kom = %s, scan_count = %s, status = %s, vrijeme = %s WHERE id = %s",
                    (new_kom, scan_count, status, vrijeme, row_id)
                )
                updated_rows += 1
            updated_barcodes += 1

        conn.commit()
    
    kom_import_previews.pop(body.token, None)

    return {
        "ok": True,
        "tura": preview["tura"],
        "updated_barcodes": updated_barcodes,
        "updated_rows": updated_rows,
        "filename": preview["filename"],
    }


@app.post("/grm/request")
def create_request(body: GrmRequestParams, request: Request):
    require_admin(request)
    try:
        return create_grm_request(
            date_from=body.from_date,
            date_to=body.to_date,
            admctr=body.admctr,
            request_id=body.request_id,
        )
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))


@app.get("/grm/request/{request_id}")
def get_request_status(request_id: str, request: Request):
    require_admin(request)
    tracked = get_tracking(request_id)
    if not tracked:
        raise HTTPException(status_code=404, detail="Request nije pronaden.")
    return tracked


@app.post("/grm/request/{request_id}/poll")
def poll_request(request_id: str, request: Request):
    require_admin(request)
    try:
        return poll_grm_request(request_id)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))


@app.post("/grm/request/{request_id}/ingest")
def ingest_request(request_id: str, request: Request):
    require_admin(request)
    try:
        return ingest_grm_request(request_id)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))


@app.get("/grm/request/{request_id}/work-orders")
def get_request_work_orders(request_id: str, request: Request):
    require_admin(request)
    try:
        return get_grm_request_work_orders(request_id)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))


@app.post("/grm/request/{request_id}/ingest-selection")
def ingest_request_selection(request_id: str, body: GrmSelectionIngest, request: Request):
    require_admin(request)
    try:
        return ingest_grm_request(request_id, selected_sifradn=body.sifradn)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))


@app.post("/grm/request/{request_id}/wait")
def wait_request(request_id: str, request: Request, timeout_seconds: int = 90):
    require_admin(request)
    try:
        return wait_and_ingest_grm_request(request_id, timeout_seconds=timeout_seconds)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
