import os
import sqlite3
from datetime import datetime
from dotenv import load_dotenv
import psycopg
from psycopg.rows import dict_row

load_dotenv()

SQLITE_DB_PATH = os.environ.get("SQLITE_DB_PATH", "kolica.db")
DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql://kolica_user:SigurnaLozinka123!@192.168.100.181:5432/kolica_dev"
)

def normalize_bool(value):
    if value in (1, "1", True, "true", "TRUE"):
        return True
    return False

def parse_vrijeme(value):
    if not value:
        return None
    val_str = str(value).strip()
    if not val_str or val_str.lower() in ("nan", "nat", ""):
        return None
    # Try common formats
    for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%dT%H:%M:%S", "%Y-%m-%d"):
        try:
            return datetime.strptime(val_str, fmt)
        except ValueError:
            continue
    return None

def main():
    print(f"Započinjem migraciju iz {SQLITE_DB_PATH} u PostgreSQL...")
    if not os.path.exists(SQLITE_DB_PATH):
        print(f"Greška: SQLite datoteka {SQLITE_DB_PATH} ne postoji!")
        return

    sqlite_conn = sqlite3.connect(SQLITE_DB_PATH)
    sqlite_conn.row_factory = sqlite3.Row

    with psycopg.connect(DATABASE_URL, row_factory=dict_row) as pg_conn:
        with pg_conn.cursor() as cur:
            # 0. Osiguravanje postojanja tablica, stupaca i indeksa
            print("Inicijaliziram tablice u PostgreSQL bazi (ukoliko ne postoje)...")
            cur.execute("""
                CREATE TABLE IF NOT EXISTS korisnici (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username TEXT NOT NULL UNIQUE,
                    password TEXT NOT NULL,
                    role TEXT NOT NULL,
                    display_name TEXT,
                    active BOOLEAN NOT NULL DEFAULT TRUE
                )
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS dijelovi (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tura TEXT NOT NULL,
                    barcode TEXT NOT NULL,
                    nalog TEXT,
                    broj_rn TEXT,
                    part TEXT,
                    kom INTEGER NOT NULL DEFAULT 1,
                    scan_count INTEGER NOT NULL DEFAULT 0,
                    materijal TEXT,
                    klasifikacija TEXT,
                    debljina NUMERIC(6, 2),
                    status TEXT NOT NULL DEFAULT 'IZREZANO',
                    kolica INTEGER,
                    tura_br TEXT,
                    operater TEXT,
                    vrijeme TIMESTAMPTZ
                )
            """)

            # Check/Add missing columns
            cur.execute("ALTER TABLE dijelovi ADD COLUMN IF NOT EXISTS broj_rn TEXT")
            cur.execute("ALTER TABLE dijelovi ADD COLUMN IF NOT EXISTS kom INTEGER DEFAULT 1")
            cur.execute("ALTER TABLE dijelovi ADD COLUMN IF NOT EXISTS scan_count INTEGER DEFAULT 0")
            cur.execute("ALTER TABLE dijelovi ADD COLUMN IF NOT EXISTS klasifikacija TEXT")
            cur.execute("ALTER TABLE dijelovi ADD COLUMN IF NOT EXISTS tura_br TEXT")

            # Indexes
            cur.execute("CREATE INDEX IF NOT EXISTS idx_barcode ON dijelovi(barcode)")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_tura ON dijelovi(tura)")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_nalog ON dijelovi(nalog)")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_dijelovi_status ON dijelovi(status)")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_dijelovi_lower_barcode ON dijelovi (lower(barcode))")

            # 1. Prijenos korisnika
            print("Pripremam korisnike...")
            sqlite_users = sqlite_conn.execute("""
                SELECT id, username, password, role, display_name, active
                FROM korisnici
            """).fetchall()

            users_data = []
            for u in sqlite_users:
                users_data.append((
                    u["id"],
                    u["username"],
                    u["password"],
                    u["role"],
                    u["display_name"],
                    normalize_bool(u["active"]),
                ))

            if users_data:
                cur.executemany("""
                    INSERT INTO korisnici
                        (id, username, password, role, display_name, active)
                    VALUES
                        (%s, %s, %s, %s, %s, %s)
                    ON CONFLICT (username) DO UPDATE SET
                        password = EXCLUDED.password,
                        role = EXCLUDED.role,
                        display_name = EXCLUDED.display_name,
                        active = EXCLUDED.active
                """, users_data)
            print(f"Uspješno preneseno/ažurirano {len(users_data)} korisnika.")

            # 2. Prijenos dijelova
            print("Pripremam dijelove za skupni unos...")
            sqlite_parts = sqlite_conn.execute("""
                SELECT
                    id, tura, barcode, nalog, broj_rn, part, kom, scan_count,
                    materijal, klasifikacija, debljina, status, kolica,
                    tura_br, operater, vrijeme
                FROM dijelovi
            """).fetchall()

            parts_data = []
            for d in sqlite_parts:
                vrijeme_val = parse_vrijeme(d["vrijeme"])
                kom_val = max(1, int(d["kom"]) if d["kom"] is not None else 1)
                scan_val = max(0, int(d["scan_count"]) if d["scan_count"] is not None else 0)
                status_val = d["status"] if d["status"] else "IZREZANO"
                parts_data.append((
                    d["id"],
                    d["tura"],
                    d["barcode"],
                    d["nalog"],
                    d["broj_rn"],
                    d["part"],
                    kom_val,
                    scan_val,
                    d["materijal"],
                    d["klasifikacija"],
                    d["debljina"],
                    status_val,
                    d["kolica"],
                    d["tura_br"],
                    d["operater"],
                    vrijeme_val,
                ))

            if parts_data:
                print("Izvršavam skupni unos (bulk insert) u PostgreSQL...")
                cur.executemany("""
                    INSERT INTO dijelovi
                        (
                            id, tura, barcode, nalog, broj_rn, part, kom,
                            scan_count, materijal, klasifikacija, debljina,
                            status, kolica, tura_br, operater, vrijeme
                        )
                    VALUES
                        (
                            %s, %s, %s, %s, %s, %s, %s,
                            %s, %s, %s, %s,
                            %s, %s, %s, %s, %s
                        )
                    ON CONFLICT (id) DO UPDATE SET
                        tura = EXCLUDED.tura,
                        barcode = EXCLUDED.barcode,
                        nalog = EXCLUDED.nalog,
                        broj_rn = EXCLUDED.broj_rn,
                        part = EXCLUDED.part,
                        kom = EXCLUDED.kom,
                        scan_count = EXCLUDED.scan_count,
                        materijal = EXCLUDED.materijal,
                        klasifikacija = EXCLUDED.klasifikacija,
                        debljina = EXCLUDED.debljina,
                        status = EXCLUDED.status,
                        kolica = EXCLUDED.kolica,
                        tura_br = EXCLUDED.tura_br,
                        operater = EXCLUDED.operater,
                        vrijeme = EXCLUDED.vrijeme
                """, parts_data)
            print(f"Uspješno preneseno/ažurirano {len(parts_data)} dijelova.")

            # 3. Reset ID sekvenci za PostgreSQL serijalne ključeve
            cur.execute("""
                SELECT setval(
                    pg_get_serial_sequence('korisnici', 'id'),
                    COALESCE((SELECT MAX(id) FROM korisnici), 1)
                )
            """)
            cur.execute("""
                SELECT setval(
                    pg_get_serial_sequence('dijelovi', 'id'),
                    COALESCE((SELECT MAX(id) FROM dijelovi), 1)
                )
            """)
        pg_conn.commit()
    sqlite_conn.close()
    print("Migracija podataka je uspješno završena!")

if __name__ == "__main__":
    main()
